version: "3"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
      - caddy:/config

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    networks:
      - web
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - web
    ports:
      - 8080:80
    volumes:
      - .:/srv
      - ./config/filebrowser.db:/database.db
      - ./config/filebrowser.json:/database.json

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      - web
    environment:
      - WEBUI_PORT=8081
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./media:/downloads
      - qbittorrent:/config

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}
    networks:
      - web
    volumes:
      - ./media:/media
      - jellyfin:/config
      - jellyfin:/cache

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    networks:
      - web
    volumes:
      - prowlarr:/config

  radarr:
    image: linuxserver/radarr:develop
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    networks:
      - web
    volumes:
      - radarr:/config
      - ./media:/movies

  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    networks:
      - web
    volumes:
      - sonarr:/config
      - ./media:/tv

volumes:
  qbittorrent:
  filebrowser:
  portainer:
  jellyfin:
  prowlarr:
  radarr:
  sonarr:
  caddy:

networks:
  web:
    external: true
