version: "3"

services:
  nordvpn:
    image: azinchen/nordvpn:latest
    container_name: nordvpn
    restart: unless-stopped
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    networks:
      - web
    ports:
      - 8080:80
    environment:
      - USER=${NORDVPN_USERNAME}
      - PASS=${NORDVPN_PASSWORD}
      - RECREATE_VPN_CRON=5 */3 * * *
      - NETWORK=192.168.1.0/24;192.168.2.0/24
      - OPENVPN_OPTS=--mute-replay-warnings

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
      - caddy:/config

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - qbittorrent:/config
      - ./media:/downloads

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}
    networks:
      - web
    volumes:
      - jellyfin:/config
      - jellyfin:/cache
      - ./media:/media

volumes:
  caddy:
  qbittorrent:
  portainer:
  jellyfin:

networks:
  web:
    external: true
