version: "3"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
      - caddy:/config

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    networks:
      - web
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - qbittorrent:/config
      - ./media:/downloads

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}
    networks:
      - web
    ports:
      - 8096:8096
    volumes:
      - jellyfin:/config
      - jellyfin:/cache
      - ./media:/media

volumes:
  caddy:
  qbittorrent:
  portainer:
  jellyfin:

networks:
  web:
    external: true
